NAME = asm

SRC = main.c \
	valid_add_func.c \
	valid_add_lable.c \
	valid_arr_func.c \
	valid_instruct.c \
	valid_instruct2.c \
	valid_lable.c \
	valid_name_com.c

all:
	@echo Compiling...
	@gcc $(SRC) ../libft/libft.a -o $(NAME)
	@echo Done